# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haproxyedit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haproxyserver',
            name='GroupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haproxyedit.HaproxyGroup'),
        ),
    ]
