# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='log_date',
            field=models.TextField(),
        ),
    ]
